name: Joachimesque
description: Un blog, enfin, à nouveau
meta_description: "Un blog, enfin, à nouveau"

markdown: kramdown
highlighter: rouge
logo: '/assets/images/profile.jpg'
paginate: 15
baseurl: '/'
base-url: '/'
domain_name: 'https://joachimesque.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://joachimesque.github.io'
author:         'Joachim'
